use anchor_lang::prelude::*;
use anchor_lang::solana_program::{instruction::{AccountMeta,Instruction},program::invoke_signed};
use anchor_lang::InstructionData;
use tcap::instruction::PayoutTcapExitV1;
use crate::tsn::{constants::TSN_MOTHER_ESCROW_SEED,errors::TsnError,state::MotherEscrow};
const TCAP: Pubkey = pubkey!("TcApT4CytBqvqEDpRYVB7Wfi6aFzmtSZdWvDsq6bp9x");
#[derive(Accounts)] pub struct RegisterTcapExitPayoutV1<'info> { #[account(mut)] pub authority:Signer<'info>, #[account(seeds=[TSN_MOTHER_ESCROW_SEED],bump=mother_escrow.bump,constraint=mother_escrow.authority==authority.key() @ TsnError::Unauthorized)] pub mother_escrow:Account<'info,MotherEscrow>, pub tcap_program:UncheckedAccount<'info>, pub config:UncheckedAccount<'info>, pub reserve:UncheckedAccount<'info>, pub asset_entry:UncheckedAccount<'info>, pub permit:UncheckedAccount<'info>, pub reserve_authority:UncheckedAccount<'info>, pub vault:UncheckedAccount<'info>, pub destination:UncheckedAccount<'info>, pub mint:UncheckedAccount<'info>, pub token_program:UncheckedAccount<'info> }
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Copy)]
pub struct RegisterTcapExitPayoutV1Args { pub destination_owner: Pubkey }
pub fn handler(ctx:Context<RegisterTcapExitPayoutV1>, args:RegisterTcapExitPayoutV1Args)->Result<()> { let data=PayoutTcapExitV1::data(&tcap::instruction::PayoutTcapExitV1{args:tcap::instructions::payout_tcap_exit_v1::PayoutTcapExitArgsV1{destination_owner:args.destination_owner}}); let ix=Instruction{program_id:TCAP,accounts:vec![AccountMeta::new(ctx.accounts.authority.key(),true),AccountMeta::new_readonly(ctx.accounts.config.key(),false),AccountMeta::new(ctx.accounts.reserve.key(),false),AccountMeta::new_readonly(ctx.accounts.asset_entry.key(),false),AccountMeta::new(ctx.accounts.permit.key(),false),AccountMeta::new_readonly(ctx.accounts.reserve_authority.key(),false),AccountMeta::new(ctx.accounts.vault.key(),false),AccountMeta::new(ctx.accounts.destination.key(),false),AccountMeta::new_readonly(ctx.accounts.mint.key(),false),AccountMeta::new_readonly(ctx.accounts.token_program.key(),false)],data}; invoke_signed(&ix,&[ctx.accounts.authority.to_account_info(),ctx.accounts.config.to_account_info(),ctx.accounts.reserve.to_account_info(),ctx.accounts.asset_entry.to_account_info(),ctx.accounts.permit.to_account_info(),ctx.accounts.reserve_authority.to_account_info(),ctx.accounts.vault.to_account_info(),ctx.accounts.destination.to_account_info(),ctx.accounts.mint.to_account_info(),ctx.accounts.token_program.to_account_info(),ctx.accounts.tcap_program.to_account_info()],&[])?; Ok(()) }
