use anchor_lang::prelude::*;
use anchor_lang::solana_program::{instruction::{AccountMeta,Instruction},program::invoke_signed};
use anchor_lang::InstructionData;
use tcap::instruction::DebitTcapExitV1;
use crate::tsn::{constants::{TSN_MOTHER_ESCROW_SEED,TSN_TCAP_AUTHORITY_SEED},errors::TsnError,state::MotherEscrow};
const TCAP: Pubkey = pubkey!("TcApT4CytBqvqEDpRYVB7Wfi6aFzmtSZdWvDsq6bp9x");
#[derive(AnchorSerialize,AnchorDeserialize,Clone,Copy)]
pub struct RegisterTcapExitDebitV1Args { pub permit_nonce:[u8;32], pub destination_commitment:[u8;32], pub mint:Pubkey, pub amount:u64, pub sequence:u64, pub sealed:[u8;48], pub seal_commitment:[u8;32], pub source_debit_signature:[u8;64] }
#[derive(Accounts)] pub struct RegisterTcapExitDebitV1<'info> { #[account(mut)] pub authority:Signer<'info>, #[account(seeds=[TSN_MOTHER_ESCROW_SEED],bump=mother_escrow.bump,constraint=mother_escrow.authority==authority.key() @ TsnError::Unauthorized)] pub mother_escrow:Account<'info,MotherEscrow>, /// CHECK: TCAP
 pub tcap_program:UncheckedAccount<'info>, pub config:UncheckedAccount<'info>, pub tip:UncheckedAccount<'info>, pub reserve:UncheckedAccount<'info>, pub liability:UncheckedAccount<'info>, pub permit:UncheckedAccount<'info>, pub system_program:Program<'info,System>, }
pub fn handler(ctx:Context<RegisterTcapExitDebitV1>,args:RegisterTcapExitDebitV1Args)->Result<()> { let data=DebitTcapExitV1::data(&tcap::instruction::DebitTcapExitV1{args:tcap::instructions::debit_tcap_exit_v1::DebitTcapExitArgsV1{permit_nonce:args.permit_nonce,destination_commitment:args.destination_commitment,mint:args.mint,amount:args.amount,sequence:args.sequence,sealed:args.sealed,seal_commitment:args.seal_commitment,source_debit_signature:args.source_debit_signature}}); let ix=Instruction{program_id:TCAP,accounts:vec![AccountMeta::new(ctx.accounts.authority.key(),true),AccountMeta::new_readonly(ctx.accounts.config.key(),false),AccountMeta::new(ctx.accounts.tip.key(),false),AccountMeta::new(ctx.accounts.reserve.key(),false),AccountMeta::new(ctx.accounts.liability.key(),false),AccountMeta::new(ctx.accounts.permit.key(),false),AccountMeta::new_readonly(ctx.accounts.system_program.key(),false)],data}; invoke_signed(&ix,&[ctx.accounts.authority.to_account_info(),ctx.accounts.config.to_account_info(),ctx.accounts.tip.to_account_info(),ctx.accounts.reserve.to_account_info(),ctx.accounts.liability.to_account_info(),ctx.accounts.permit.to_account_info(),ctx.accounts.system_program.to_account_info(),ctx.accounts.tcap_program.to_account_info()],&[])?; Ok(()) }
